-- CÁLCULO ARITMÉTICO

/*

OS OPERADORES ARITMÉTICOS SÃO:
(+) - ADIÇÃO
(-) - SUBTRAÇÃO
(*) - MULTIPLICAÇÃO
(/) - DIVISÃO

*/

-- MULTIPLICANDO DOS NÚMEROS
SELECT 2 * 4
FROM dual;

-- AS REGRAS DE PRECEDÊNCIA DE OPERADORES ARITMÉTICOS SÃO APLICADAS NO SQL
SELECT 10 * 12 / 3 - 1
FROM dual;

-- UTILIZANDO PARÊNTESES PARA ESPECIFICAR A ORDEM DE EXECUÇÃO
SELECT 10 * (12 / 3 - 1)
FROM dual;

-- UTILIZANDO ADIÇÃO E SUBTRAÇÃO COM DATAS, SOMA DOIS DIAS
SELECT TO_DATE('13-MAI-2022') + 2
FROM dual;

-- SUBTRAIR UMA DATA DE OUTRA, RESULTADO EM NÚMERO DE DIAS ENTRE AS DUAS DATAS
SELECT TO_DATE('13-MAI-2022') - TO_DATE('01-MAI-2022')
FROM dual;

-- OPERAÇÕES ARITMÉTICAS DE COLUNAS
SELECT nm_produto, preco, preco + 2
FROM tb_produtos;
