-- COMPARANDO VALORES

-- RECUPERA VALORES DIFERENTE DE 2
SELECT *
FROM tb_clientes
WHERE id_cliente <> 2;

-- RECUPERAR VALORES MAIOR QUE 2
SELECT *
FROM tb_clientes
WHERE id_cliente > 2;

-- RECUPERA A TRÊS PRIMEIRAS LINHAS UTILIZANDO ROWNUN E <=3

SELECT ROWNUM, id_produto, nm_produto
FROM tb_produtos
WHERE ROWNUM <= 3;

-- RECUPERA LINHA ONDE O VALOR DA COLUNA É MAIOR DO QUE QUALQUER UM DOS VALORES
-- OPERADORES UTILIZADOS (=, <>, <, >, <=, >=)
SELECT *
FROM tb_clientes
WHERE id_cliente > ANY(2, 3, 4);

-- RECUPERA VALORES ONDE ID_CLIENTE É MAIOR QUE OS VALORES 2, 3, 4
SELECT *
FROM tb_clientes
WHERE id_cliente > ALL(2, 3, 4);





