-- PRECEDÊNCIA DE OPERADORES

-- "AND" TERÁ PRECEDÊNCIA SOBRE "OR"
-- OPERADORES DE COMPARAÇÃO TEM PRECEDÊNCIA SOBRE "AND"
-- UTILIZAR () PARA INDICAR A ORDEM QUE DESEJA EXECUTAR A EXPRESSÕES

SELECT *
FROM tb_clientes
WHERE dt_nascimento > '01/JAN/1970'
OR id_cliente < 2
AND telefone LIKE '%1211';