-- ORDER BY

-- USADA PARA CLASSIFICAR AS LINHA RECUPERADAS POR UMA CONSULTA

-- EXEMPLO 1

SELECT *
FROM tb_clientes
ORDER BY sobrenome;

-- DESC: UTILIZADA PARA CLASSIFICAR EM ORDEM DECRESCENTE;
-- ASC: UTILIZADA PARA CLASSIFICAR EM ORDEM CRESCENTE (DEFAULT);

-- EXEMPLO 2

SELECT *
FROM tb_clientes
ORDER BY nome ASC;

SELECT *
FROM tb_clientes
ORDER BY sobrenome DESC;

-- UM NÚMERO DA COLUNA PODE SER USADO PARA INDICAR QUAL COLUNA DEVE SER CLASSIFICADA

SELECT id_cliente, nome, sobrenome
FROM tb_clientes
ORDER BY 2;

