-- IDENTIFICADORES DE LINHA

-- IDENTIFICADOR EXCLUSIVO ROWID (ARMAZENA LOCALIZAÇÃO FÍSICA DA LINHA)
SELECT ROWID, id_cliente
FROM tb_clientes;

-- UTILIZANDO O DESCRIBE, A COLUNA ROWID NÃO APARECE, POIS ELA É UTLIZADA
-- INTERNAMENTE PELO BD.
DESCRIBE tb_clientes;
